//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyApp.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clasic.
        /// </summary>
        internal static string Classic {
            get {
                return ResourceManager.GetString("Classic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic Plus.
        /// </summary>
        internal static string ClassicPlus {
            get {
                return ResourceManager.GetString("ClassicPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card.
        /// </summary>
        internal static string CreditCard {
            get {
                return ResourceManager.GetString("CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Account.
        /// </summary>
        internal static string CurrentAccount {
            get {
                return ResourceManager.GetString("CurrentAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Account Plus.
        /// </summary>
        internal static string CurrentAccountPlus {
            get {
                return ResourceManager.GetString("CurrentAccountPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit Card.
        /// </summary>
        internal static string DebitCard {
            get {
                return ResourceManager.GetString("DebitCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold.
        /// </summary>
        internal static string Gold {
            get {
                return ResourceManager.GetString("Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold Credit Card.
        /// </summary>
        internal static string GoldCreditCard {
            get {
                return ResourceManager.GetString("GoldCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        internal static string Income {
            get {
                return ResourceManager.GetString("Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        internal static string IsStudent {
            get {
                return ResourceManager.GetString("IsStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junior Saver.
        /// </summary>
        internal static string JuniorSaver {
            get {
                return ResourceManager.GetString("JuniorSaver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junior Saver Account.
        /// </summary>
        internal static string JuniorSaverAccount {
            get {
                return ResourceManager.GetString("JuniorSaverAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have an account.
        /// </summary>
        internal static string MustSelectAccount {
            get {
                return ResourceManager.GetString("MustSelectAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age missing.
        /// </summary>
        internal static string NoAge {
            get {
                return ResourceManager.GetString("NoAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income missing.
        /// </summary>
        internal static string NoIncome {
            get {
                return ResourceManager.GetString("NoIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not selected account..
        /// </summary>
        internal static string NoSelectedAccount {
            get {
                return ResourceManager.GetString("NoSelectedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not selected any card..
        /// </summary>
        internal static string NoSelectedCards {
            get {
                return ResourceManager.GetString("NoSelectedCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you student?.
        /// </summary>
        internal static string NoStudent {
            get {
                return ResourceManager.GetString("NoStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a student.
        /// </summary>
        internal static string NotStudent {
            get {
                return ResourceManager.GetString("NotStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is {0}.
        /// </summary>
        internal static string SelectedAcount {
            get {
                return ResourceManager.GetString("SelectedAcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You selected cards: {0}.
        /// </summary>
        internal static string SelectedCards {
            get {
                return ResourceManager.GetString("SelectedCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        internal static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Account.
        /// </summary>
        internal static string StudentAccount {
            get {
                return ResourceManager.GetString("StudentAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too old.
        /// </summary>
        internal static string TooOld {
            get {
                return ResourceManager.GetString("TooOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too poor.
        /// </summary>
        internal static string TooPoor {
            get {
                return ResourceManager.GetString("TooPoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too rich.
        /// </summary>
        internal static string TooRitch {
            get {
                return ResourceManager.GetString("TooRitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too young.
        /// </summary>
        internal static string TooYoung {
            get {
                return ResourceManager.GetString("TooYoung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
